import type { ProjectFromTransaction } from 'components/types/transactions';
import Image from 'next/future/image';

type ProjectDetailsProps = {
  data: ProjectFromTransaction;
};

const ProjectDetails = ({ data }: ProjectDetailsProps): JSX.Element => {
  const { contribution, cover_picture, creditsAvailable, name, sectors, tagline } = data;

  return (
    <>
      <h2 className='text-xl'>Credits generated by</h2>
      <div className='flex flex-col lg:flex-row gap-5'>
        <div className='relative lg:w-24 w-full h-24  rounded-lg overflow-hidden'>
          <Image
            src={cover_picture}
            alt=''
            fill
            sizes='(max-width:640px) 90vw, (min-width:1024px) 12rem, 45vw'
            className='object-cover'
          />
        </div>
        <div className='space-y-1.5'>
          <div>
            <span className='block'>Project:</span>
            <span className='block font-medium'>{tagline}</span>
          </div>
          <div>
            Developer: <span className='font-medium'>{name}</span>
          </div>
          <div className='text-text-secondary'>
            Sectors: <span className='font-medium'>{sectors.join(', ')}</span>
          </div>
        </div>
      </div>
      <div className='space-y-1.5'>
        <span className='block'>
          Total CO2 contributed: <span className='font-medium'>{contribution} tCO2</span>
        </span>
        <span className='block'>
          Carbon credits still available: <span className='font-medium'>{creditsAvailable}</span>
        </span>
      </div>
    </>
  );
};

export default ProjectDetails;
