import type { ProjectFromTransaction } from 'components/types/transactions';
import Image from 'next/future/image';

type ProjectDetailsProps = {
  data: ProjectFromTransaction;
};

const ProjectDetails = ({ data }: ProjectDetailsProps): JSX.Element => {
  const { contribution, cover_picture, creditsAvailable, name, sectors, tagline } = data;

  return (
    <>
      <h2 className='text-xl'>Credits generated by</h2>
      <div className='flex gap-5'>
        <div className='relative w-24 rounded-lg overflow-hidden'>
          <Image src={cover_picture} alt='' fill sizes='6rem' className='object-cover' />
        </div>
        <div className='space-y-1.5'>
          <div>
            <span className='block'>Project:</span>
            <span className='block font-medium'>{tagline}</span>
          </div>
          <div>
            Developer: <span className='font-medium'>{name}</span>
          </div>
          <div className='text-text-secondary'>
            Sectors: <span className='font-medium'>{sectors.join(', ')}</span>
          </div>
        </div>
      </div>
      <div className='space-y-1.5'>
        <span className='block'>
          Total CO2 contributed: <span className='font-medium'>{contribution} tCO2</span>
        </span>
        <span className='block'>
          Carbon credits still available: <span className='font-medium'>{creditsAvailable}</span>
        </span>
      </div>
    </>
  );
};

export default ProjectDetails;
