import Head from 'next/head';
import WidgetWrapper from '../components/widgets/WidgetWrapper/WidgetWrapper';
import Organization from '../components/Organization.widget';
import BillingInformation from '../components/BillingInformation.widget';
import useSWR, { mutate } from 'swr';
import { AddNewUsersForm } from '../components/forms/forms';
import WidgetsGrid from 'components/WidgetsGrid';

// TODO: parse

const fetcher = (url: URL) => fetch(url).then(res => res.json());

const getOrgURL = 'api/protected/get-organization';

// 8 columns 2 rows
const gridTemplateAreas = {
  all: '" org org org org org bill bill bill"'
};

export default function Home () {
  const { data, error } = useSWR(getOrgURL, fetcher);
  if (error) {
    return (
      <p className='text-xl text-center max-w-lg mx-auto'>
        Error encountered while getting information. Try to refresh the page and contact our team in the problem
        persists.
      </p>
    );
  }
  return (
    <>
      <Head>
        <title>Riverse projects</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <WidgetsGrid gridTemplateAreas={gridTemplateAreas}>
        <>
          <WidgetWrapper areaName='org'>
            {data ? (
              <Organization data={data.organization.organization}>
                <AddNewUsersForm />
              </Organization>
            ) : (
              <h2>Loading...</h2>
            )}
          </WidgetWrapper>
          <WidgetWrapper areaName='bill'>
            {data ? <BillingInformation data={data.organization.billingInfo} /> : <h2>Loading...</h2>}
          </WidgetWrapper>
        </>
      </WidgetsGrid>
    </>
  );
}
