import Head from 'next/head';

import ContributionWidget from 'components/ContributionWidget';
import Documentation from 'components/widgets/Documentation';
import Projects from 'components/widgets/Projects';
import TotalCreditsWidget from 'components/TotalCredits.widget';
import WidgetWrapper from 'components/widgets/WidgetWrapper';
import WidgetsGrid from 'components/WidgetsGrid';

// 8 columns 2 rows
const gridTemplateAreas = {
  all: '"pr pr pr pr pr pr contr contr" "pr pr pr pr pr pr creds creds" "docs docs docs docs docs docs . ."'
  // all: '"pr pr pr pr . . contr contr" "pr pr pr pr . . creds creds" "docs docs docs docs docs docs . ."'
};

const Page = () => (
  <>
    <Head>
      <title>Riverse Dashboard welcome page</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.png' />
    </Head>
    <WidgetsGrid gridTemplateAreas={gridTemplateAreas}>
      <>
        <WidgetWrapper areaName='pr'>
          <Projects limit={4} />
        </WidgetWrapper>
        <WidgetWrapper areaName='contr'>
          <ContributionWidget />
        </WidgetWrapper>
        <WidgetWrapper areaName='creds'>
          <TotalCreditsWidget />
        </WidgetWrapper>
        <WidgetWrapper areaName='docs'>
          <Documentation />
        </WidgetWrapper>
      </>
    </WidgetsGrid>
  </>
);

export default Page;
