import Head from 'next/head';

import getFilters from '../components/db/getFilters';

import { useState } from 'react';
import widgetStyles from '../styles/WidgetStyles.module.css';
import ProjectsWithFilters from '../components/ProjectsWithFilters';
import WidgetWrapper from '../components/WidgetWrapper';
import pageStyles from '../styles/Pages.module.css';
import Filters from '../components/Filters.widget';

// TODO:
// 1. get filters!!!

export default function Home({ filtersData }) {
  const [appliedFilters, setAppliedFilters] = useState({});

  return (
    <>
      <Head>
        <title>Riverse projects</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className={`main-container ${pageStyles.projects}`}>
        <div className={widgetStyles['widgets-wrapper']}>
          <WidgetWrapper columns={3} areaName='projects'>
            <ProjectsWithFilters appliedFilters={appliedFilters} />
          </WidgetWrapper>
          <WidgetWrapper columns={1} areaName='filters'>
            <Filters data={filtersData} setFilters={setAppliedFilters} appliedFilters={appliedFilters} />
          </WidgetWrapper>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const filtersArray = ['sectors', 'mechanism', 'country'];

  const data = await getFilters(process.env.API_KEY, process.env.DB_VIEW, filtersArray);

  const staticFilters = [
    {
      name: 'years',
      label: 'Vintage year',
      values: [2021, 2022, 2023, 2024, 2025, 2026],
    },
  ];

  return {
    props: {
      filtersData: [...data, ...staticFilters],
    },
    revalidate: 860,
  };

  // [
  //   {
  //     name: 'sectors',
  //     values: [
  //       'Waste',
  //       'Agriculture',
  //       'Mobility & transport',
  //       'Construction & housing',
  //       'Industry',
  //       'Energy'
  //     ],
  //     label: 'Sectors'
  //   },
  //   {
  //     name: 'mechanism',
  //     values: ['Avoidance', 'Reduction', 'Removal'],
  //     label: 'Mechanism'
  //   },
  //   {
  //     name: 'country',
  //     values: ['France', 'Belgium', 'United Kingdom'],
  //     label: 'Country'
  //   }
  // ]
}
