import Head from 'next/head'
import DashBoard from '../components/Dashboard'

export default function Home () {
  return (
    <main>
      <Head>
        <title>Riverse Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <DashBoard />
    </main>
  )
}
