import Head from 'next/head'
import Dashboard from '../components/Dashboard'

function GuestUserScreen () {
  return (
    <>
      <Head>
        <title>Riverse Dashboard welcome page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className='main-container'>
        <Dashboard />
      </main>
    </>
  )
}

export default GuestUserScreen
