import Head from 'next/head'
import pageStyles from '../styles/Pages.module.css'
import widgetStyles from '../styles/WidgetStyles.module.css'
// import Contribution from './Contribution'
import ContributionWidget from '../components/ContributionWidget'
import Documentation from '../components/Documentation'
import Projects from '../components/Projects'
import TotalCreditsWidget from '../components/TotalCredits.widget'
import WidgetWrapper from '../components/WidgetWrapper'

function Page () {
  return (
    <>
      <Head>
        <title>Riverse Dashboard welcome page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className={`main-container ${pageStyles.dashboard}`}>
        <div className={widgetStyles['widgets-wrapper']}>
          <WidgetWrapper areaName='projects'>
            <Projects limit={4} />
          </WidgetWrapper>
          <WidgetWrapper areaName='contribution'>
            <ContributionWidget />
          </WidgetWrapper>
          <WidgetWrapper areaName='credits'>
            <TotalCreditsWidget />
          </WidgetWrapper>
          <WidgetWrapper areaName='docs'>
            <Documentation />
          </WidgetWrapper>
        </div>{' '}
      </main>
    </>
  )
}

export default Page
