import Head from 'next/head'
import widgetStyles from '../styles/WidgetStyles.module.css'
import WidgetWrapper from '../components/WidgetWrapper'
import Organization from '../components/Organization.widget'
import styles from '../styles/Members.page.module.css'
import BillingInformation from '../components/BillingInformation.widget'
import OrganizationDocuments from '../components/OrganizationDocuments.widget'

// TODO: parse

export default function Home () {
  return (
    <>
      <Head>
        <title>Riverse projects</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main
        className={`${widgetStyles['widgets-wrapper']} main-container ${styles.page}`}
      >
        <WidgetWrapper columns={3} areaName='organization'>
          <Organization />
        </WidgetWrapper>
        {/* <WidgetWrapper columns={1} areaName='docs'>
          <OrganizationDocuments />
        </WidgetWrapper> */}
        <WidgetWrapper columns={3} areaName='billing'>
          <BillingInformation />
        </WidgetWrapper>
      </main>
    </>
  )
}
