import Head from 'next/head'
import widgetStyles from '../styles/WidgetStyles.module.css'
import WidgetWrapper from '../components/WidgetWrapper'
import Organization from '../components/Organization.widget'
import BillingInformation from '../components/BillingInformation.widget'
import OrganizationDocuments from '../components/OrganizationDocuments.widget'
import pageStyles from '../styles/Pages.module.css'

// TODO: parse

export default function Home () {
  return (
    <>
      <Head>
        <title>Riverse projects</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className={`main-container ${pageStyles.members}`}>
        <div className={widgetStyles['widgets-wrapper']}>
          <WidgetWrapper columns={3} areaName='organization'>
            <Organization />
          </WidgetWrapper>
          {/* <WidgetWrapper columns={1} areaName='docs'>
          <OrganizationDocuments />
        </WidgetWrapper> */}
          <WidgetWrapper columns={3} areaName='billing'>
            <BillingInformation />
          </WidgetWrapper>
        </div>
      </main>
    </>
  )
}
