import Head from 'next/head'

// TODO:
// 1.delete scroll

export default function Home () {
  return (
    <main className='main-container'>
      <Head>
        <title>Riverse orders</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <h2>Hello you</h2>
      <h3>This page is currently in progress</h3>
    </main>
  )
}
