import Head from 'next/head'
import widgetStyles from '../styles/WidgetStyles.module.css'
import Projects from '../components/Projects'

// TODO:

export default function Home () {
  return (
    <>
      <Head>
        <title>Riverse projects</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className={`${widgetStyles['widgets-wrapper']} main-container`}>
        <Projects columns={3} />
      </main>
    </>
  )
}
